Create .gitattributes
mattiverse/Laravel-Userstamps pull request #55
Opened 2024-06-07 18:34 UTC by imanghafoori1

when installed by composer in the vendor directory, these files and folders are excluded.

2025-02-22 19:52 UTC, mattmcdev requested changes
Thanks for this. Can you make the couple small changes highlighted and I’ll get it merged

2025-02-22 19:52 UTC, mattmcdev commented on .gitattributes
> +# Path-based git attributes
Please remove the comment lines

2025-02-22 19:52 UTC, mattmcdev commented on .gitattributes
> +/.travis.yml        export-ignore
Tests have moved from Travis so don’t need this line anymore

2025-02-24 19:55 UTC, imanghafoori1 commented
Done

2025-02-25 12:35 UTC, merged

2025-02-25 12:36 UTC, mattmcdev commented
Thank you